import {
  Loader2,
  Upload,
  Save,
  Plus,
  Trash2,
  List,
  ArrowLeft,
  GripVertical,
  CornerDownRight,
  MoreVertical,
  Folder,
  Pencil,
  Check,
  X,
  FolderOpen,
  Scan,
  Github,
  LayoutDashboard,
  Settings,
  Menu,
  Database,
  LogOut,
  User,
  ChevronLeft,
  ChevronRight,
  PanelRightOpen,
  PanelLeftClose,
  Search,
} from "lucide-react"

export type Icon = typeof Loader2

export const Icons = {
  spinner: Loader2,
  upload: Upload,
  save: Save,
  add: Plus,
  trash: Trash2,
  list: List,
  back: ArrowLeft,
  grip: GripVertical,
  corner: CornerDownRight,
  more: MoreVertical,
  folder: Folder,
  edit: Pencil,
  check: Check,
  close: X,
  empty: FolderOpen,
  scan: Scan,
  gitHub: Github,
  dashboard: LayoutDashboard,
  settings: Settings,
  menu: Menu,
  database: Database,
  logOut: LogOut,
  user: User,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  panelRightOpen: PanelRightOpen,
  panelLeftClose: PanelLeftClose,
  search: Search,
} 