import {
  Loader2,
  Upload,
  Save,
  Plus,
  Trash2,
  List,
  ArrowLeft,
  GripVertical,
  CornerDownRight,
  MoreVertical,
  Folder,
  Pencil,
  Check,
  X,
  FolderOpen,
  Scan,
  Github,
  LayoutDashboard,
  Settings,
  Menu,
  Database,
  LogOut,
  User,
  ChevronLeft,
  ChevronRight,
  PanelRightOpen,
  PanelLeftClose,
  Search,
  Home,
  BookOpen,
  Bookmark,
  Heart,
  Star,
  Mail,
  MessageSquare,
  Calendar,
  Image,
  Globe,
  Link,
  FileText,
  Library,
  Newspaper,
  Rocket,
  Target,
  Trophy,
  Video,
  Music,
  Users,
  Briefcase,
  Coffee,
  Code,
  Cloud,
  Command,
  Compass,
  Crown,
  Gift,
  Headphones,
  Map,
  Monitor,
  Package,
  Phone,
  Printer,
  Radio,
  Shield,
  Smartphone,
  Sun,
  Terminal,
  Tool,
  Tv,
  Zap,
  type Icon as LucideIcon,
  Navigation,
  Clock
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  spinner: Loader2,
  upload: Upload,
  save: Save,
  add: Plus,
  trash: Trash2,
  list: List,
  back: ArrowLeft,
  grip: GripVertical,
  corner: CornerDownRight,
  more: MoreVertical,
  folder: Folder,
  edit: Pencil,
  check: Check,
  close: X,
  empty: FolderOpen,
  scan: Scan,
  gitHub: Github,
  dashboard: LayoutDashboard,
  settings: Settings,
  menu: Menu,
  database: Database,
  logout: LogOut,
  user: User,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  panelLeft: PanelLeftClose,
  panelRight: PanelRightOpen,
  panelLeftClose: PanelLeftClose,
  panelRightOpen: PanelRightOpen,
  search: Search,
  home: Home,
  book: BookOpen,
  bookmark: Bookmark,
  heart: Heart,
  star: Star,
  mail: Mail,
  message: MessageSquare,
  calendar: Calendar,
  image: Image,
  globe: Globe,
  link: Link,
  file: FileText,
  library: Library,
  news: Newspaper,
  rocket: Rocket,
  target: Target,
  trophy: Trophy,
  video: Video,
  music: Music,
  users: Users,
  briefcase: Briefcase,
  coffee: Coffee,
  code: Code,
  cloud: Cloud,
  command: Command,
  compass: Compass,
  crown: Crown,
  gift: Gift,
  headphones: Headphones,
  map: Map,
  monitor: Monitor,
  package: Package,
  phone: Phone,
  printer: Printer,
  radio: Radio,
  shield: Shield,
  smartphone: Smartphone,
  sun: Sun,
  terminal: Terminal,
  tool: Tool,
  tv: Tv,
  zap: Zap,
  category: Folder,
  placeholder: Folder,
  logo: Navigation,
  clock: Clock
} as const